export const personas = [
  {
    id: 1,
    nombre: "Clark",
    apellido: "Kent",
    edad: 45,
    alterEgo: "Superman",
    ciudad: "Metropolis",
    publicado: 2002,
  },
  {
    id: 2,
    nombre: "Bruce",
    apellido: "Wayne",
    edad: 35,
    alterEgo: "Batman",
    ciudad: "Gotica",
    publicado: 2012,
  },
  {
    id: 3,
    nombre: "Bart",
    apellido: "Alen",
    edad: 30,
    alterEgo: "Flash",
    ciudad: "Central",
    publicado: 2017,
  },
  {
    id: 4,
    nombre: "Lex",
    apellido: "Luthor",
    edad: 18,
    enemigo: "Superman",
    robos: 500,
    asesinatos: 7,
  },
  {
    id: 5,
    nombre: "Harvey",
    apellido: "Dent",
    edad: 20,
    enemigo: "Batman",
    robos: 750,
    asesinatos: 2,
  },
  {
    id: 666,
    nombre: "Celina",
    apellido: "kyle",
    edad: 23,
    enemigo: "Batman",
    robos: 25,
    asesinatos: 1,
  },
];
